#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

Out1=HDMI-0
Out0=DP-5

bspc monitor $Out1 -d 1 2 3 4 5 6
bspc monitor $Out0 -d 7 8 9 10

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
bspc rule -a Nm-connection-editor state=floating
bspc rule -a Pavucontrol state=floating

#Autostart applications
xrandr --output $Out1 --primary --right-of $Out0 &
lxsession &
xfce4-clipman &
picom &
nitrogen --restore &
$HOME/.config/polybar/launch.sh --hack &
dunst &
setxkbmap -layout us,gr -option grp:win_space_toggle &
xset m 1 1 &
export QT_STYLE_OVERRIDE=kvantum &
wmname LG3D 

